# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-java:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: singularitynet/java-sdk-integration-test-env:3.0.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run tests!
      - run:
          name: Build and run tests
          command: |
            mvn -DskipITs=false install

      - save_cache:
          key: maven-artifacts-{{ .Revision }}
          paths:
            - ~/.m2
          name: Save maven artifacts

      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Build CLI examples
          command: |
            cd ./example/cli
            mvn install

      - run:
          name: Build and run tutorial app
          command: |
            cd ./example/tutorial
            mvn package exec:java

  build-android:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-28

    working_directory: ~/repo

    environment:
      ETHEREUM_ENDPOINT: https://mainnet.infura.io/v3/e7732e1f679e461b9bb4da5653ac3fc2
      GRADLE_OPTS: -Xmx3200m -Dorg.gradle.daemon=false

    steps:
      - checkout

      - restore_cache:
          key: maven-artifacts-{{ .Revision }}
          name: Restoring maven artifacts from previous job

      - run:
          name: Build Android examples
          command: |
            cd ./example/android/SNetDemo
            cat <<EOF >./ethereum.properties
            ethereum.json.rpc.endpoint=$ETHEREUM_ENDPOINT
            EOF
            ./gradlew build

workflows:
  version: 2
  build:
    jobs:
      - build-java
      - build-android:
          requires:
            - build-java
