# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # get dependencies
      - run:
          name: Get dependencies
          command: |
            curl -L https://get.web3j.io | bash
            source $HOME/.web3j/source.sh
            ./get_contracts.sh
      # run tests!
      - run:
          name: Run tests
          command: mvn test
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Compile javadoc
          command: mvn javadoc:javadoc
