# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: singularitynet/java-sdk-integration-test-env:2.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run tests!
      - run:
          name: Build and run tests
          command: |
            mvn -DskipITs=false install
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Build CLI examples
          command: |
            cd ./example
            cat <<EOF >./ethereum.properties
            ethereum.json.rpc.endpoint=https://mainnet.infura.io/v3/${SINGNET_INFURA_PROJECT_ID}
            EOF
            mvn install

      - run:
          name: Build Android examples
          command: |
            cd ./example/android/SNetDemo
            cat <<EOF >./ethereum.properties
            cat <<EOF >./ethereum.properties
            ethereum.json.rpc.endpoint=https://mainnet.infura.io/v3/${SINGNET_INFURA_PROJECT_ID}
            EOF
            ./gradlew
